### PR TITLE
Stuff

### PR DESCRIPTION
**Pull request by Fryguy**

### CODE REVIEW

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/12ac2c3850ab89a81acbd62681e4804514e6bd87 with rubocop 0.32.1 and haml-lint 0.13.0
1 file checked, 1 offense detected

**Gemfile**
- [ ] :large_orange_diamond: - [Line 42](https://github.com/miq-test/sandbox/blob/12ac2c3850ab89a81acbd62681e4804514e6bd87/Gemfile#L42), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.32.1/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/3774312593f1199319ef403473d702261360b801 with rubocop 0.32.1 and haml-lint 0.13.0
1 file checked, 1 offense detected

**Gemfile**
- [ ] :large_orange_diamond: - [Line 43](https://github.com/miq-test/sandbox/blob/3774312593f1199319ef403473d702261360b801/Gemfile#L43), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.32.1/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/73e351536147813ea0ccf91c9c862a86da84a030 with rubocop 0.32.1 and haml-lint 0.13.0
1 file checked, 1 offense detected

**Gemfile**
- [ ] :large_orange_diamond: - [Line 42](https://github.com/miq-test/sandbox/blob/73e351536147813ea0ccf91c9c862a86da84a030/Gemfile#L42), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.32.1/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/7cc147cb681e5d4491b2db1d13ca5338279f1571 with rubocop 0.32.1 and haml-lint 0.13.0
1 file checked, 2 offenses detected

**Gemfile**
- [ ] :large_orange_diamond: - [Line 1](https://github.com/miq-test/sandbox/blob/7cc147cb681e5d4491b2db1d13ca5338279f1571/Gemfile#L1), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.32.1/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.
- [ ] :large_orange_diamond: - [Line 43](https://github.com/miq-test/sandbox/blob/7cc147cb681e5d4491b2db1d13ca5338279f1571/Gemfile#L43), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.32.1/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/1da5f512a221e74d0ec414ef01d64e724f330a7b with rubocop 0.32.1 and haml-lint 0.13.0
1 file checked, 1 offense detected

**Gemfile**
- [ ] :large_orange_diamond: - [Line 42](https://github.com/miq-test/sandbox/blob/1da5f512a221e74d0ec414ef01d64e724f330a7b/Gemfile#L42), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.32.1/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/ef76e826ea88af000d1bbbbe3f5b747e9101b636 with rubocop 0.32.1 and haml-lint 0.13.0
1 file checked, 1 offense detected

**Gemfile**
- [ ] :large_orange_diamond: - [Line 40](https://github.com/miq-test/sandbox/blob/ef76e826ea88af000d1bbbbe3f5b747e9101b636/Gemfile#L40), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.32.1/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.

**Comment by miq-bot-testing** [comment]
<github_pr_commenter_batch />
* Gemfile changes detected in commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/1da5f512a221e74d0ec414ef01d64e724f330a7b.

**Comment by miq-bot-testing** [comment]
<github_pr_commenter_batch />
* Gemfile changes detected in commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/ef76e826ea88af000d1bbbbe3f5b747e9101b636.

**Comment by miq-bot-testing** [comment]
<github_pr_commenter_batch />
* Gemfile changes detected in commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/1da5f512a221e74d0ec414ef01d64e724f330a7b.

**Comment by miq-bot-testing** [comment]
<github_pr_commenter_batch />
* Gemfile changes detected in commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/7a896c3895f0c862363f49c7f545ac1b24c98050.

**Comment by miq-bot-testing** [comment]
<github_pr_commenter_batch />
* Gemfile changes detected in commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/7a896c3895f0c862363f49c7f545ac1b24c98050.

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/7a896c3895f0c862363f49c7f545ac1b24c98050 with rubocop 0.32.1 and haml-lint 0.13.0
1 file checked, 1 offense detected

**Gemfile**
- [ ] :large_orange_diamond: - [Line 41](https://github.com/miq-test/sandbox/blob/7a896c3895f0c862363f49c7f545ac1b24c98050/Gemfile#L41), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.32.1/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.

**Comment by miq-bot-testing** [comment]
<github_pr_commenter_batch />
* Gemfile changes detected in commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/8b6ce25b6b3bfb63a58e6d134f6c4edd4d4dc994.

**Comment by miq-bot-testing** [comment]
<github_pr_commenter_batch />
* Gemfile changes detected in commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/8b6ce25b6b3bfb63a58e6d134f6c4edd4d4dc994.

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/8b6ce25b6b3bfb63a58e6d134f6c4edd4d4dc994 with rubocop 0.33.0 and haml-lint 0.13.0
1 file checked, 1 offense detected

**Gemfile**
- [ ] :large_orange_diamond: - [Line 40](https://github.com/miq-test/sandbox/blob/8b6ce25b6b3bfb63a58e6d134f6c4edd4d4dc994/Gemfile#L40), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.33.0/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/62503431873d2da31f3319377096aa8befcba67f with rubocop 0.33.0 and haml-lint 0.13.0
1 file checked, 1 offense detected

**Gemfile**
- [ ] :large_orange_diamond: - [Line 38](https://github.com/miq-test/sandbox/blob/62503431873d2da31f3319377096aa8befcba67f/Gemfile#L38), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.33.0/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.

**Comment by miq-bot-testing** [comment]
<github_pr_commenter_batch />
* Gemfile changes detected in commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/62503431873d2da31f3319377096aa8befcba67f.

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/53013e7f4c84f2c48fc71c7a979282773cde4e54 with rubocop 0.33.0 and haml-lint 0.13.0
1 file checked, 1 offense detected

**Gemfile**
- [ ] :large_orange_diamond: - [Line 37](https://github.com/miq-test/sandbox/blob/53013e7f4c84f2c48fc71c7a979282773cde4e54/Gemfile#L37), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.33.0/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.

**Comment by miq-bot-testing** [comment]
<github_pr_commenter_batch />
* Gemfile changes detected in commits https://github.com/miq-test/sandbox/compare/731c37a31036bb59dafc498044782a0ec5b4b3d2...53013e7f4c84f2c48fc71c7a979282773cde4e54.

**Comment by miq-bot-testing** [comment]
<github_pr_commenter_batch />
* Gemfile changes detected in commits https://github.com/miq-test/sandbox/compare/731c37a31036bb59dafc498044782a0ec5b4b3d2...468d5a4a188de479e3942214281464334b25a649.

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/468d5a4a188de479e3942214281464334b25a649 with rubocop 0.33.0 and haml-lint 0.13.0
1 file checked, 1 offense detected

**Gemfile**
- [ ] :large_orange_diamond: - [Line 36](https://github.com/miq-test/sandbox/blob/468d5a4a188de479e3942214281464334b25a649/Gemfile#L36), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.33.0/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/fb2480b76994123b3316282dc47beee3cbdc6fa4 with rubocop 0.33.0 and haml-lint 0.13.0
1 file checked, 1 offense detected

**Gemfile**
- [ ] :large_orange_diamond: - [Line 35](https://github.com/miq-test/sandbox/blob/fb2480b76994123b3316282dc47beee3cbdc6fa4/Gemfile#L35), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.33.0/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.

**Comment by miq-bot-testing** [comment]
<github_pr_commenter_batch />Detected issues with the commits in https://github.com/miq-test/sandbox/compare/731c37a31036bb59dafc498044782a0ec5b4b3d2...fb2480b76994123b3316282dc47beee3cbdc6fa4
* Gemfile changes detected.

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/fb2480b76994123b3316282dc47beee3cbdc6fa4 with rubocop 0.32.1 and haml-lint 0.13.0
1 file checked, 1 offense detected

**Gemfile**
- [ ] :large_orange_diamond: - [Line 35](https://github.com/miq-test/sandbox/blob/fb2480b76994123b3316282dc47beee3cbdc6fa4/Gemfile#L35), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.32.1/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/fb2480b76994123b3316282dc47beee3cbdc6fa4 with rubocop 0.33.0 and haml-lint 0.13.0
1 file checked, 1 offense detected

**Gemfile**
- [ ] :large_orange_diamond: - [Line 35](https://github.com/miq-test/sandbox/blob/fb2480b76994123b3316282dc47beee3cbdc6fa4/Gemfile#L35), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.33.0/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/fb2480b76994123b3316282dc47beee3cbdc6fa4 with rubocop 0.33.0 and haml-lint 0.13.0
1 file checked, 1 offense detected

**Gemfile**
- [ ] :large_orange_diamond: - [Line 35](https://github.com/miq-test/sandbox/blob/fb2480b76994123b3316282dc47beee3cbdc6fa4/Gemfile#L35), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.33.0/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/compare/731c37a31036bb59dafc498044782a0ec5b4b3d2...8570882a51ab1ea7370bd1b2e284d43b0e30dbea with rubocop 0.33.0 and haml-lint 0.13.0
1 file checked, 1 offense detected

**Gemfile**
- [ ] :large_orange_diamond: - [Line 30](https://github.com/miq-test/sandbox/blob/8570882a51ab1ea7370bd1b2e284d43b0e30dbea/Gemfile#L30), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.33.0/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.

**Comment by miq-bot-testing** [comment]
<github_pr_commenter_batch />Detected potential issues with the commits in https://github.com/miq-test/sandbox/compare/731c37a31036bb59dafc498044782a0ec5b4b3d2...8570882a51ab1ea7370bd1b2e284d43b0e30dbea
* Gemfile changes detected.

**Comment by jrafanie** [comment]
@miq-bot-testing add_label bug

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/compare/731c37a31036bb59dafc498044782a0ec5b4b3d2~...8570882a51ab1ea7370bd1b2e284d43b0e30dbea with ruby 2.2.3, rubocop 0.34.2, and haml-lint 0.13.0
1 file checked, 1 offense detected

**Gemfile**
- [ ] :large_orange_diamond: - [Line 30](https://github.com/miq-test/sandbox/blob/8570882a51ab1ea7370bd1b2e284d43b0e30dbea/Gemfile#L30), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.34.2/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.

**Comment by jrafanie** [comment]
@miq-bot-testing rm_label bug

**Comment by miq-bot-testing** [comment]
<github_pr_commenter_batch />Some comments on commits https://github.com/miq-test/sandbox/compare/731c37a31036bb59dafc498044782a0ec5b4b3d2~...8570882a51ab1ea7370bd1b2e284d43b0e30dbea
* Gemfile changes detected. /cc @chrisarcand

**Comment by miq-bot-testing** [comment]
<github_pr_commenter_batch />Some comments on commits https://github.com/miq-test/sandbox/compare/731c37a31036bb59dafc498044782a0ec5b4b3d2~...8570882a51ab1ea7370bd1b2e284d43b0e30dbea
* Gemfile changes detected. /cc @chrisarcand

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/compare/731c37a31036bb59dafc498044782a0ec5b4b3d2~...8570882a51ab1ea7370bd1b2e284d43b0e30dbea with ruby 2.2.3, rubocop 0.34.2, and haml-lint 0.13.0
1 file checked, 1 offense detected

**Gemfile**
- [ ] :large_orange_diamond: - [Line 30](https://github.com/miq-test/sandbox/blob/8570882a51ab1ea7370bd1b2e284d43b0e30dbea/Gemfile#L30), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.34.2/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/compare/731c37a31036bb59dafc498044782a0ec5b4b3d2~...8570882a51ab1ea7370bd1b2e284d43b0e30dbea with ruby 2.2.5, rubocop 0.37.2, and haml-lint 0.16.1
1 file checked, 1 offense detected

**Gemfile**
- [ ] :exclamation: - [Line 30](https://github.com/miq-test/sandbox/blob/8570882a51ab1ea7370bd1b2e284d43b0e30dbea/Gemfile#L30), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.37.2/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/compare/731c37a31036bb59dafc498044782a0ec5b4b3d2~...8570882a51ab1ea7370bd1b2e284d43b0e30dbea with ruby 2.2.5, rubocop 0.37.2, and haml-lint 0.16.1
1 file checked, 1 offense detected

**\*\***
- [ ] :bomb: :boom: :fire: :fire_engine: - Linter/Rubocop - missing config files

**Comment by miq-bot-testing** [comment]
<pr-mergeability-checker />This pull request is not mergeable.  Please rebase and repush.

**Comment by miq-bot-testing** [comment]
<pr-mergeability-checker />This pull request is not mergeable.  Please rebase and repush.

**Comment by d-m-u** [comment]
This pull request has been automatically closed because it has not been updated for at least 6 months.

Feel free to reopen this pull request if these changes are still valid.

Thank you for all your contributions!

**Pull request closed without merging**
