### PR TITLE
PR with a single BZ

### PR DESCRIPTION
**Pull request by Fryguy**
https://partner-bugzilla.redhat.com/show_bug.cgi?id=1473783

### CODE REVIEW

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commit https://github.com/Fryguy/sandbox/commit/68fc1f12a6f2f4ea351ff9c1b7c7772f52c3dd7b with ruby 2.3.3, rubocop 0.52.0, haml-lint 0.20.0, and yamllint 1.10.0
0 files checked, 0 offenses detected
Everything looks fine. :star:

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/Fryguy/sandbox/compare/68fc1f12a6f2f4ea351ff9c1b7c7772f52c3dd7b~...3e337851c17efd35483e70d555d88ff7971b5835 with ruby 2.3.3, rubocop 0.52.0, haml-lint 0.20.0, and yamllint 1.10.0
0 files checked, 0 offenses detected
Everything looks fine. :cake:

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/Fryguy/sandbox/compare/68fc1f12a6f2f4ea351ff9c1b7c7772f52c3dd7b~...e4146229145e6b885ca85e5c5d7618cf7ba38303 with ruby 2.3.3, rubocop 0.52.0, haml-lint 0.20.0, and yamllint 1.10.0
0 files checked, 0 offenses detected
Everything looks fine. :cookie:

**Comment by miq-bot-testing** [comment]
<pr-mergeability-checker />This pull request is not mergeable.  Please rebase and repush.

**Comment by miq-bot-testing** [comment]
<pr-mergeability-checker />This pull request is not mergeable.  Please rebase and repush.

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/Fryguy/sandbox/compare/68fc1f12a6f2f4ea351ff9c1b7c7772f52c3dd7b~...e4146229145e6b885ca85e5c5d7618cf7ba38303 with ruby 2.3.3, rubocop 0.52.0, haml-lint 0.20.0, and yamllint 1.10.0
0 files checked, 0 offenses detected
Everything looks fine. :trophy:

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/Fryguy/sandbox/compare/68fc1f12a6f2f4ea351ff9c1b7c7772f52c3dd7b~...e4146229145e6b885ca85e5c5d7618cf7ba38303 with ruby 2.3.3, rubocop 0.52.0, haml-lint 0.20.0, and yamllint 1.10.0
0 files checked, 0 offenses detected
Everything looks fine. :star:

**Comment by d-m-u** [comment]
<rubocop />Checked commits https://github.com/Fryguy/sandbox/compare/68fc1f12a6f2f4ea351ff9c1b7c7772f52c3dd7b~...e4146229145e6b885ca85e5c5d7618cf7ba38303 with ruby 2.3.8, rubocop 0.69.0, haml-lint 0.20.0, and yamllint 1.17.0
0 files checked, 0 offenses detected
Everything looks fine. :star:

**Pull request closed without merging**
