### PR TITLE
[NON_MASTER_TARGET] README STUFF

### PR DESCRIPTION
**Pull request by Fryguy**

### CODE REVIEW

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commit https://github.com/Fryguy/sandbox/commit/56d18d0fd29862cefd639284e1da312e410e1723 with ruby 2.2.5, rubocop 0.37.2, and haml-lint 0.16.1
0 files checked, 0 offenses detected
Everything looks good. :star:

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commit https://github.com/Fryguy/sandbox/commit/56d18d0fd29862cefd639284e1da312e410e1723 with ruby 2.3.3, rubocop 0.47.1, haml-lint 0.20.0, and yamllint 1.10.0
0 files checked, 0 offenses detected
Everything looks fine. :trophy:

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commit https://github.com/Fryguy/sandbox/commit/56d18d0fd29862cefd639284e1da312e410e1723 with ruby 2.3.3, rubocop 0.47.1, haml-lint 0.20.0, and yamllint 1.10.0
0 files checked, 0 offenses detected
Everything looks fine. :trophy:

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commit https://github.com/Fryguy/sandbox/commit/56d18d0fd29862cefd639284e1da312e410e1723 with ruby 2.3.3, rubocop 0.52.0, haml-lint 0.20.0, and yamllint 1.10.0
0 files checked, 0 offenses detected
Everything looks fine. :+1:

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commit https://github.com/Fryguy/sandbox/commit/56d18d0fd29862cefd639284e1da312e410e1723 with ruby 2.3.3, rubocop 0.52.0, haml-lint 0.20.0, and yamllint 1.10.0
0 files checked, 0 offenses detected
Everything looks fine. :+1:

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commit https://github.com/Fryguy/sandbox/commit/56d18d0fd29862cefd639284e1da312e410e1723 with ruby 2.3.3, rubocop 0.52.0, haml-lint 0.20.0, and yamllint 1.10.0
0 files checked, 0 offenses detected
Everything looks fine. :star:

**Comment by d-m-u** [comment]
<rubocop />Checked commit https://github.com/Fryguy/sandbox/commit/56d18d0fd29862cefd639284e1da312e410e1723 with ruby 2.3.8, rubocop 0.69.0, haml-lint 0.20.0, and yamllint 1.17.0
0 files checked, 0 offenses detected
Everything looks fine. :+1:

**Pull request closed without merging**
