### PR TITLE
Bump gem

### PR DESCRIPTION
**Pull request by jrafanie**

### CODE REVIEW

**Comment by miq-bot-testing** [comment]
<github_pr_commenter_batch />Some comments on commits https://github.com/jrafanie/sandbox/compare/917a412ed067198b5e33c3a44c7a88d97c6e3442~...3e5b6c301a7ccc521ab1e36dda8ccee0be697052
* Gemfile changes detected.

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/jrafanie/sandbox/compare/917a412ed067198b5e33c3a44c7a88d97c6e3442~...3e5b6c301a7ccc521ab1e36dda8ccee0be697052 with ruby 2.2.3, rubocop 0.34.2, and haml-lint 0.13.0
3 files checked, 2 offenses detected

**app/controllers/application_controller.rb**
- [ ] :red_circle: **Warn** - [Line 5](https://github.com/jrafanie/sandbox/blob/3e5b6c301a7ccc521ab1e36dda8ccee0be697052/app/controllers/application_controller.rb#L5), Col 5 - [Lint/UselessAssignment](http://rubydoc.info/gems/rubocop/0.34.2/RuboCop/Cop/Lint/UselessAssignment) - Useless assignment to variable - `really_long_line`.

**app/views/layouts/application.html.haml**
- [ ] :red_circle: **Error** - [Line 13](https://github.com/jrafanie/sandbox/blob/3e5b6c301a7ccc521ab1e36dda8ccee0be697052/app/views/layouts/application.html.haml#L13), Col  -  - You don't need to use "- end" in Haml. Un-indent to close a block:
- if foo?
  %strong Foo!
- else
  Not foo.
%p This line is un-indented, so it isn't part of the "if" block

**Comment by jrafanie** [comment]
@miq-bot-testing add_label bug

**Comment by miq-bot-testing** [comment]
<github_pr_commenter_batch />Some comments on commits https://github.com/jrafanie/sandbox/compare/917a412ed067198b5e33c3a44c7a88d97c6e3442~...3e5b6c301a7ccc521ab1e36dda8ccee0be697052
* Gemfile changes detected. /cc @chrisarcand

**Comment by miq-bot-testing** [comment]
<github_pr_commenter_batch />Some comments on commits https://github.com/jrafanie/sandbox/compare/917a412ed067198b5e33c3a44c7a88d97c6e3442~...3e5b6c301a7ccc521ab1e36dda8ccee0be697052
* Gemfile changes detected. /cc @chrisarcand

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/jrafanie/sandbox/compare/917a412ed067198b5e33c3a44c7a88d97c6e3442~...3e5b6c301a7ccc521ab1e36dda8ccee0be697052 with ruby 2.2.3, rubocop 0.34.2, and haml-lint 0.13.0
3 files checked, 4 offenses detected

**app/controllers/application_controller.rb**
- [ ] :red_circle: **Warn** - [Line 5](https://github.com/jrafanie/sandbox/blob/3e5b6c301a7ccc521ab1e36dda8ccee0be697052/app/controllers/application_controller.rb#L5), Col 5 - [Lint/UselessAssignment](http://rubydoc.info/gems/rubocop/0.34.2/RuboCop/Cop/Lint/UselessAssignment) - Useless assignment to variable - `really_long_line`.
- [ ] :large_orange_diamond: - [Line 5](https://github.com/jrafanie/sandbox/blob/3e5b6c301a7ccc521ab1e36dda8ccee0be697052/app/controllers/application_controller.rb#L5), Col 24 - [Style/StringLiterals](http://rubydoc.info/gems/rubocop/0.34.2/RuboCop/Cop/Style/StringLiterals) - Prefer single-quoted strings when you don't need string interpolation or special symbols.
- [ ] :large_orange_diamond: - [Line 5](https://github.com/jrafanie/sandbox/blob/3e5b6c301a7ccc521ab1e36dda8ccee0be697052/app/controllers/application_controller.rb#L5), Col 81 - [Metrics/LineLength](http://rubydoc.info/gems/rubocop/0.34.2/RuboCop/Cop/Metrics/LineLength) - Line is too long. [88/80]

**app/views/layouts/application.html.haml**
- [ ] :red_circle: **Error** - [Line 13](https://github.com/jrafanie/sandbox/blob/3e5b6c301a7ccc521ab1e36dda8ccee0be697052/app/views/layouts/application.html.haml#L13), Col  -  - You don't need to use "- end" in Haml. Un-indent to close a block:
- if foo?
  %strong Foo!
- else
  Not foo.
%p This line is un-indented, so it isn't part of the "if" block

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/jrafanie/sandbox/compare/917a412ed067198b5e33c3a44c7a88d97c6e3442~...3e5b6c301a7ccc521ab1e36dda8ccee0be697052 with ruby 2.2.5, rubocop 0.37.2, and haml-lint 0.16.1
3 files checked, 2 offenses detected

**app/controllers/application_controller.rb**
- [ ] :warning: - [Line 5](https://github.com/jrafanie/sandbox/blob/3e5b6c301a7ccc521ab1e36dda8ccee0be697052/app/controllers/application_controller.rb#L5), Col 5 - [Lint/UselessAssignment](http://rubydoc.info/gems/rubocop/0.37.2/RuboCop/Cop/Lint/UselessAssignment) - Useless assignment to variable - `really_long_line`.

**app/views/layouts/application.html.haml**
- [ ] :bomb: :boom: :fire: :fire_engine: - [Line 13](https://github.com/jrafanie/sandbox/blob/3e5b6c301a7ccc521ab1e36dda8ccee0be697052/app/views/layouts/application.html.haml#L13) - You don't need to use "- end" in Haml. Un-indent to close a block:
- if foo?
  %strong Foo!
- else
  Not foo.
%p This line is un-indented, so it isn't part of the "if" block

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/jrafanie/sandbox/compare/917a412ed067198b5e33c3a44c7a88d97c6e3442~...3e5b6c301a7ccc521ab1e36dda8ccee0be697052 with ruby 2.2.5, rubocop 0.37.2, and haml-lint 0.16.1
3 files checked, 2 offenses detected

**\*\***
- [ ] :bomb: :boom: :fire: :fire_engine: - Linter/Haml - missing config files
- [ ] :bomb: :boom: :fire: :fire_engine: - Linter/Rubocop - missing config files

**Pull request closed without merging**
