### PR TITLE
[WIP] Add thing to stuffs a

### PR DESCRIPTION
**Pull request by Fryguy**

### CODE REVIEW

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commit https://github.com/Fryguy/sandbox/commit/c02fa35c7b370f111c8d36f94795952eee6cbf82 with ruby 2.2.5, rubocop 0.37.2, and haml-lint 0.16.1
2 files checked, 0 offenses detected
Everything looks good. :cake:

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commit https://github.com/Fryguy/sandbox/commit/c02fa35c7b370f111c8d36f94795952eee6cbf82 with ruby 2.2.5, rubocop 0.37.2, and haml-lint 0.16.1
2 files checked, 1 offense detected

**\*\***
- [ ] :bomb: :boom: :fire: :fire_engine: - Linter/Rubocop - missing config files

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commit https://github.com/Fryguy/sandbox/commit/c02fa35c7b370f111c8d36f94795952eee6cbf82 with ruby 2.3.3, rubocop 0.47.1, haml-lint 0.20.0, and yamllint 1.10.0
2 files checked, 1 offense detected

**\*\***
- [ ] :bomb: :boom: :fire: :fire_engine: - Linter/Rubocop - missing config files

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commit https://github.com/Fryguy/sandbox/commit/c02fa35c7b370f111c8d36f94795952eee6cbf82 with ruby 2.3.3, rubocop 0.47.1, haml-lint 0.20.0, and yamllint 1.10.0
2 files checked, 1 offense detected

**\*\***
- [ ] :bomb: :boom: :fire: :fire_engine: - Linter/Rubocop - missing config files

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commit https://github.com/Fryguy/sandbox/commit/c02fa35c7b370f111c8d36f94795952eee6cbf82 with ruby 2.3.3, rubocop 0.52.0, haml-lint 0.20.0, and yamllint 1.10.0
2 files checked, 1 offense detected

**\*\***
- [ ] :bomb: :boom: :fire: :fire_engine: - Linter/Rubocop - missing config files

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commit https://github.com/Fryguy/sandbox/commit/c02fa35c7b370f111c8d36f94795952eee6cbf82 with ruby 2.3.3, rubocop 0.52.0, haml-lint 0.20.0, and yamllint 1.10.0
2 files checked, 1 offense detected

**\*\***
- [ ] :bomb: :boom: :fire: :fire_engine: - Linter/Rubocop - missing config files

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commit https://github.com/Fryguy/sandbox/commit/c02fa35c7b370f111c8d36f94795952eee6cbf82 with ruby 2.3.3, rubocop 0.52.0, haml-lint 0.20.0, and yamllint 1.10.0
2 files checked, 1 offense detected

**\*\***
- [ ] :bomb: :boom: :fire: :fire_engine: - Linter/Rubocop - missing config files

**Comment by d-m-u** [comment]
<rubocop />Checked commit https://github.com/Fryguy/sandbox/commit/c02fa35c7b370f111c8d36f94795952eee6cbf82 with ruby 2.3.8, rubocop 0.69.0, haml-lint 0.20.0, and yamllint 1.17.0
2 files checked, 1 offense detected

**\*\***
- [ ] :bomb: :boom: :fire: :fire_engine: - Linter/Rubocop - missing config files

**Pull request closed without merging**
