### PR TITLE
Add a test that'll stall travis.

### PR DESCRIPTION
**Pull request by imtayadeway**

### CODE REVIEW

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commit https://github.com/imtayadeway/sandbox/commit/9cab5240baeb6a8118caa664c7862880d6901b38 with rubocop 0.32.1 and haml-lint 0.13.0
1 file checked, 0 offenses detected
Everything looks good. :+1:

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commit https://github.com/imtayadeway/sandbox/commit/9cab5240baeb6a8118caa664c7862880d6901b38 with rubocop 0.33.0 and haml-lint 0.13.0
1 file checked, 0 offenses detected
Everything looks good. :star:

**Comment by imtayadeway** [comment]
@miq-bot add-label bug

**Comment by imtayadeway** [comment]
@miq-bot remove-label bug

**Comment by imtayadeway** [comment]
@miq-bot add-label wontfix

**Comment by imtayadeway** [comment]
@miq-bot remove-label wontfix

**Comment by imtayadeway** [comment]
@miq-bot add-label wontfix

**Comment by imtayadeway** [comment]
@miq-bot rm-label wontfix

**Comment by imtayadeway** [comment]
notification

**Pull request closed without merging**
