### PR TITLE
Stuff

### PR DESCRIPTION
**Pull request by Fryguy**

### CODE REVIEW

**Comment by Fryguy** [comment]
@miq_bot add_label bug

**Comment by Fryguy** [comment]
@miq-bot add_label bug

**Comment by Fryguy** [comment]
@Fryguy add_label question

**Comment by Fryguy** [comment]
<rubocop />Checked commit https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 with rubocop 0.32.1 and haml-lint 0.13.0
0 files checked, 0 offenses detected
Everything looks good. :cookie:

**Comment by Fryguy** [comment]
@Fryguy add_label bug

**Comment by Fryguy** [comment]
@miq-bot-testing add_label bug

**Comment by Fryguy** [comment]
@miq-bot-testing add_label bug

**Comment by Fryguy** [comment]
@miq-bot-testing add_label new_label_1

**Comment by Fryguy** [comment]
@miq-bot-testing add_label doesnt_exist

**Comment by miq-bot-testing** [comment]
@Fryguy Cannot apply the following label(s) because they are not recognized: doesnt_exist

**Comment by Fryguy** [comment]
@miq-bot-testing add_label doesnt_exist, enhancement

**Comment by miq-bot-testing** [comment]
@Fryguy Cannot apply the following label(s) because they are not recognized: doesnt_exist

**Comment by Fryguy** [comment]
@miq-bot-testing set_milestone Milestone1

**Comment by Fryguy** [comment]
@miq-bot-testing assign @Fryguy

**Comment by Fryguy** [comment]
@miq-bot-testing assign @Fryguy

**Comment by Fryguy** [comment]
@miq-bot-testing set_milestone MilestoneDoesntExist

**Comment by miq-bot-testing** [comment]
@Fryguy Milestone MilestoneDoesntExist is not recognized, ignoring...

**Comment by Fryguy** [comment]
@miq-bot-testing set_milestone Milestone2

**Comment by Fryguy** [comment]
@miq-bot-testing set_milestone Milestone1

**Comment by Fryguy** [comment]
@miq-bot-testing add_label bug, invalid, other, new_label_2

**Comment by miq-bot-testing** [comment]
@Fryguy Cannot apply the following labels because they are not recognized: other

**Comment by Fryguy** [comment]
@miq-bot-testing add_label new_label_3

**Comment by Fryguy** [comment]
@miq-bot-testing rm-labels new_label_1, new_label_2, new_label_3, new_label_4

**Comment by miq-bot-testing** [comment]
@Fryguy Cannot remove the following label(s) because they are not recognized: new_label_4

**Comment by Fryguy** [comment]
@miq-bot-testing remove_labels bug, enhancement

**Comment by Fryguy** [comment]
@miq-bot-testing remove_labels x, y

**Comment by miq-bot-testing** [comment]
@Fryguy Cannot remove the following labels because they are not recognized: x, y

**Comment by Fryguy** [comment]
@miq-bot-testing add_labels invalid, bug

**Comment by Fryguy** [comment]
Testing a cached label, but deleted in the repo
@miq-bot-testing add_labels new_label_3

**Comment by Fryguy** [comment]
@miq-bot-testing assign @jrafanie

**Comment by Fryguy** [comment]
@miq-bot-testing assign @gtanzillo

**Comment by Fryguy** [comment]
@miq-bot-testing assign @chessbyte

**Comment by miq-bot-testing** [comment]
@Fryguy @chessbyte is an invalid user, ignoring...

**Comment by Fryguy** [comment]
@miq-bot-testing add_label enhancement

**Comment by Fryguy** [comment]
@miq-bot-testing something

**Comment by Fryguy** [comment]
@miq-bot-testing something

**Comment by Fryguy** [comment]
@miq-bot-testing something_else

**Comment by Fryguy** [comment]
@miq-bot-testing add_label bug

**Comment by Fryguy** [comment]
@miq-bot-testing add_label bug

**Comment by Fryguy** [comment]
@miq-bot-testing add_label bug

**Comment by Fryguy** [comment]
@miq-bot-testing add_label bug

**Comment by Fryguy** [comment]
@miq-bot-testing add_label bug

**Comment by Fryguy** [comment]
@miq-bot-testing add_label question

**Comment by Fryguy** [comment]
@miq-bot-testing add_label question

**Comment by Fryguy** [comment]
@miq-bot-testing add_label question

**Comment by Fryguy** [comment]
@miq-bot-testing rm_label question

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/72eb486f0284da317975ba0e1df43786e3e09e24 with rubocop 0.32.1 and haml-lint 0.13.0
0 files checked, 0 offenses detected
Everything looks good. :+1:

**Comment by miq-bot-testing** [comment]
<gemfile_checker />Gemfile changes detected in commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/12ac2c3850ab89a81acbd62681e4804514e6bd87.

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/miq-test/sandbox/commit/731c37a31036bb59dafc498044782a0ec5b4b3d2 .. https://github.com/miq-test/sandbox/commit/12ac2c3850ab89a81acbd62681e4804514e6bd87 with rubocop 0.32.1 and haml-lint 0.13.0
1 file checked, 1 offense detected

**Gemfile**
- [ ] :large_orange_diamond: - [Line 42](https://github.com/miq-test/sandbox/blob/12ac2c3850ab89a81acbd62681e4804514e6bd87/Gemfile#L42), Col 1 - [Style/LeadingCommentSpace](http://rubydoc.info/gems/rubocop/0.32.1/RuboCop/Cop/Style/LeadingCommentSpace) - Missing space after #.

**Pull request closed without merging**
