### PR TITLE
Testasdfasdf

### PR DESCRIPTION
**Pull request by chrisarcand**
stuff

### CODE REVIEW

**Comment by miq-bot-testing** [comment]
<github_pr_commenter_batch />Some comments on commit https://github.com/chrisarcand/sandbox-1/commit/95b56734e6898f1c47cb766fdad483e2392076f0
* Gemfile changes detected. /cc @chrisarcand

**Comment by notchrisarcand** [comment]
<rubocop />Checked commit https://github.com/chrisarcand/sandbox-1/commit/95b56734e6898f1c47cb766fdad483e2392076f0 with ruby 2.2.3, rubocop 0.34.2, and haml-lint 0.13.0
1 file checked, 0 offenses detected
Everything looks good. :cake:

**Comment by miq-bot-testing** [comment]
<github_pr_commenter_batch />Some comments on commit https://github.com/chrisarcand/sandbox-1/commit/95b56734e6898f1c47cb766fdad483e2392076f0
* Gemfile changes detected. /cc @chrisarcand

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commit https://github.com/chrisarcand/sandbox-1/commit/95b56734e6898f1c47cb766fdad483e2392076f0 with ruby 2.2.3, rubocop 0.34.2, and haml-lint 0.13.0
1 file checked, 0 offenses detected
Everything looks good. :cake:

**Comment by chrisarcand** [comment]
test

**Comment by chrisarcand** [comment]
Another test

**Comment by chrisarcand** [comment]
test

**Comment by chrisarcand** [comment]
asdf

**Comment by chrisarcand** [comment]
asdf

**Comment by chrisarcand** [comment]
test

**Comment by chrisarcand** [comment]
test

**Comment by chrisarcand** [comment]
trigger

**Comment by miq-bot-testing** [comment]
<rubocop />Checked commits https://github.com/chrisarcand/sandbox-1/compare/95b56734e6898f1c47cb766fdad483e2392076f0~...9210feed7887ea315e4766b6ab69d0ed35b11ff2 with ruby 2.2.3, rubocop 0.34.2, and haml-lint 0.13.0
0 files checked, 0 offenses detected
Everything looks good. :+1:

**Comment by miq-bot-testing** [comment]
<github_pr_commenter_batch />Some comments on commits https://github.com/chrisarcand/sandbox-1/compare/95b56734e6898f1c47cb766fdad483e2392076f0~...9210feed7887ea315e4766b6ab69d0ed35b11ff2
- Gemfile changes detected. /cc @chrisarcand

**Pull request closed without merging**
